version: '3.7'

services:

  node:
    container_name: back-end
    image: back-end
    build:
      context: ./back-end
    ports:
      - "4000:5000"
    networks:
      - my-network
    volumes:
      - C:\Projects\Docker\first-3-tier-docker-try\back-end:/var/www
    depends_on:
      - mongodb

  mongodb:
    container_name: db
    image: mongo
    networks:
      - my-network
      
  front-end:
    container_name: front-end
    image: front-end
    build:
      context: ./front-end
    ports:
      - "4050:80"
    networks:
      - my-network
    volumes:
      - C:\Projects\Docker\first-3-tier-docker-try\front-end:/usr/share/nginx/html
    depends_on:
      - node

networks:
  my-network:
    driver: bridge